spring:
  security:
    user:
      name: participantUser
      password: zb!XztG34
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration
security:
  enable-csrf: false

a1pms:
  baseUrl: http://a1policymanagement.onap:8081
  headers:
    content-type: application/json
  endpoints:
    health: /a1-policy/v2/rics
    services: /a1-policy/v2/services
    service: /a1-policy/v2/services/{service_id}

participant:
  intermediaryParameters:
    reportingTimeIntervalMs: 120000
    description: Participant Description
    participantId:
      name: A1PMSParticipant0
      version: 1.0.0
    participantType:
      name: org.onap.policy.clamp.acm.A1PMSParticipant
      version: 2.3.4
    clampAutomationCompositionTopics:
      topicSources:
        - topic: POLICY-ACRUNTIME-PARTICIPANT
          servers:
            - ${topicServer:localhost}
          topicCommInfrastructure: dmaap
          fetchTimeout: 15000
      topicSinks:
        - topic: POLICY-ACRUNTIME-PARTICIPANT
          servers:
            - ${topicServer:localhost}
          topicCommInfrastructure: dmaap


management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics, prometheus
server:
  port: 8086
  servlet:
    context-path: /onap/policy/clamp/acm/a1pmsparticipant