spring:
  security:
    user:
      name: runtimeUser
      password: zb!XztG34
  mvc:
    converters:
      preferred-json-mapper: gson
  datasource:
    url: jdbc:postgresql://${postgresql.host:postgres}:${postgresql.port:5432}/clampacm
    driverClassName: org.postgresql.jdbc.Driver
    username: policy_user
    password: policy_user
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.onap.policy.common.spring.utils.CustomImplicitNamingStrategy
    properties:
      hibernate:
        format_sql: true

security:
  enable-csrf: false

server:
  servlet:
    context-path: /onap/policy/clamp/acm
  port: 6969
  error:
    path: /error

runtime:
  topics:
    operationTopic: policy-acruntime-participant
    syncTopic: acm-ppnt-sync
  participantParameters:
    heartBeatMs: 20000
    maxStatusWaitMs: 200000
  topicParameterGroup:
    topicSources:
      -
        topic: ${runtime.topics.operationTopic}
        servers:
          - ${topicServer:kafka:9092}
        topicCommInfrastructure: NOOP
        fetchTimeout: 15000
        useHttps: true
    topicSinks:
      -
        topic: ${runtime.topics.operationTopic}
        servers:
          - ${topicServer:kafka:9092}
        topicCommInfrastructure: NOOP
        useHttps: true
      -
        topic: ${runtime.topics.syncTopic}
        servers:
          - ${topicServer:kafka:9092}
        topicCommInfrastructure: NOOP
        useHttps: true
  acmParameters:
    toscaElementName: org.onap.policy.clamp.acm.AutomationCompositionElement
    toscaCompositionName: org.onap.policy.clamp.acm.AutomationComposition

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      show-components: always
