spring:
  security:
    user:
      name: participantUser
      password: zb!XztG34
security:
  enable-csrf: false
participant:
  intermediaryParameters:
    reportingTimeIntervalMs: 120000
    description: Participant Description
    participantId:
      name: HttpParticipant0
      version: 1.0.0
    participantType:
      name: org.onap.policy.clamp.acm.HttpParticipant
      version: 2.3.4
    clampAutomationCompositionTopics:
      topicSources:
        - topic: POLICY-ACRUNTIME-PARTICIPANT
          servers:
            - ${topicServer:message-router}
          topicCommInfrastructure: dmaap
          fetchTimeout: 15000
          useHttps: true
      topicSinks:
        - topic: POLICY-ACRUNTIME-PARTICIPANT
          servers:
            - ${topicServer:message-router}
          topicCommInfrastructure: dmaap
          useHttps: true
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
server:
  port: 8084
  servlet:
    context-path: /onap/policy/clamp/acm/httpparticipant
