spring:
  security:
    user:
      name: participantUser
      password: zb!XztG34
security:
  enable-csrf: false

participant:
  localChartDirectory: /home/policy/local-charts
  infoFileName: CHART_INFO.json
  intermediaryParameters:
    reportingTimeIntervalMs: 120000
    description: Participant Description
    participantId:
      name: K8sParticipant0
      version: 1.0.0
    participantType:
      name: org.onap.policy.clamp.acm.KubernetesParticipant
      version: 2.3.4
    clampAutomationCompositionTopics:
      topicSources:
        -
          topic: POLICY-ACRUNTIME-PARTICIPANT
          servers:
            - ${topicServer:message-router}
          topicCommInfrastructure: dmaap
          fetchTimeout: 15000
          useHttps: true
      topicSinks:
        -
          topic: POLICY-ACRUNTIME-PARTICIPANT
          servers:
            - ${topicServer:message-router}
          topicCommInfrastructure: dmaap
          useHttps: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
server:
  port: 8083
  servlet:
    context-path: /onap/policy/clamp/acm/k8sparticipant

logging:
  # Configuration of logging
  level:
    ROOT: ERROR
    org.springframework: ERROR
    org.springframework.data: ERROR
    org.springframework.web.reactive.function.client.ExchangeFunctions: ERROR
    org.onap.policy.clamp.acm.participant.kubernetes: INFO
  file:
    name: /var/log/onap/policy/clamp/application.log

chart:
  api:
    enabled: false
