spring:
  security:
    user:
      name: healthcheck
      password: zb!XztG34
security:
  enable-csrf: false

participant:
  localChartDirectory: /home/policy/local-charts
  infoFileName: CHART_INFO.json
  intermediaryParameters:
    reportingTimeIntervalMs: 120000
    description: Participant Description
    participantId:
      name: K8sParticipant0
      version: 1.0.0
    participantType:
      name: org.onap.k8s.controlloop.K8SControlLoopParticipant
      version: 2.3.4
    clampControlLoopTopics:
      topicSources:
        -
          topic: POLICY-CLRUNTIME-PARTICIPANT
          servers:
            - ${topicServer:message-router}
          topicCommInfrastructure: dmaap
          fetchTimeout: 15000
          useHttps: true
      topicSinks:
        -
          topic: POLICY-CLRUNTIME-PARTICIPANT
          servers:
            - ${topicServer:message-router}
          topicCommInfrastructure: dmaap
          useHttps: true

management:
  endpoints:
    web:
      exposure:
        include: "loggers,logfile,health,info,metrics,threaddump,heapdump"
server:
  port: 8083
  servlet:
    context-path: /onap/k8sparticipant

logging:
  # Configuration of logging
  level:
    ROOT: INFO
    org.springframework: ERROR
    org.springframework.data: ERROR
    org.springframework.web.reactive.function.client.ExchangeFunctions: ERROR
  file:
    name: /var/log/onap/policy/clamp/application.log
