spring:
  security:
    user:
      name: participantUser
      password: zb!XztG34
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration

security:
  enable-csrf: false

participant:
  localChartDirectory: /home/policy/local-charts
  infoFileName: CHART_INFO.json
  intermediaryParameters:
    topics:
      operationTopic: policy-acruntime-participant
      syncTopic: acm-ppnt-sync
    reportingTimeIntervalMs: 120000
    description: Participant Description
    participantId: 101c62b3-8918-41b9-a747-d21eb79c6c02
    clampAutomationCompositionTopics:
      topicSources:
        -
          topic: ${participant.intermediaryParameters.topics.operationTopic}
          servers:
            - ${topicServer:kafka:9092}
          topicCommInfrastructure: NOOP
          fetchTimeout: 15000
          useHttps: true
        -
          topic: ${participant.intermediaryParameters.topics.syncTopic}
          servers:
            - ${topicServer:kafka:9092}
          topicCommInfrastructure: NOOP
          fetchTimeout: 15000
          useHttps: true
      topicSinks:
        -
          topic: ${participant.intermediaryParameters.topics.operationTopic}
          servers:
            - ${topicServer:kafka:9092}
          topicCommInfrastructure: NOOP
          useHttps: true
    participantSupportedElementTypes:
      -
        typeName: org.onap.policy.clamp.acm.K8SMicroserviceAutomationCompositionElement
        typeVersion: 1.0.0

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      show-components: always

server:
  port: 8083
  servlet:
    context-path: /onap/policy/clamp/acm/k8sparticipant

logging:
  # Configuration of logging
  level:
    ROOT: ERROR
    org.springframework: ERROR
    org.springframework.data: ERROR
    org.springframework.web.reactive.function.client.ExchangeFunctions: ERROR
    org.onap.policy.clamp.acm.participant.kubernetes: INFO
  file:
    name: /var/log/onap/policy/clamp/application.log

chart:
  api:
    enabled: false

# Update the config here for permitting repositories and protocols
helm:
  repos:
    -
      repoName: kong
      address: https://charts.konghq.com
    -
      repoName: bitnami
      address: https://charts.bitnami.com/bitnami

  protocols:
    - http
    - https
