export enum ControlLoopState {
  UNINITIALISED = 'UNINITIALISED',
  UNINITIALISED2PASSIVE = 'UNINITIALISED2PASSIVE',
  PASSIVE = 'PASSIVE',
  PASSIVE2RUNNING = 'PASSIVE2RUNNING',
  RUNNING = 'RUNNING',
  RUNNING2PASSIVE = 'RUNNING2PASSIVE',
  PASSIVE2UNINITIALISED = 'PASSIVE2UNINITIALISED'
}
