spring:
  application:
    name: pf-ppnt
  security:
    user:
      name: ${HTTP_USER:participantUser}
      password: ${HTTP_PASSWORD:zb!XztG34}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration

participant:
  pdpGroup: defaultGroup
  pdpType: apex
  policyApiParameters:
    clientName: api
    hostname: policy-api
    port: 6969
    userName: ${API_USER}
    password: ${API_PASSWORD}
    useHttps: false
    allowSelfSignedCerts: true
  policyPapParameters:
    clientName: pap
    hostname: policy-pap
    port: 6969
    userName: ${PAP_USER}
    password: ${PAP_PASSWORD}
    useHttps: false
    allowSelfSignedCerts: true
  intermediaryParameters:
    failUnsupportedOperation: false
    topics:
      operationTopic: policy-acruntime-participant
      syncTopic: acm-ppnt-sync
    threadPoolSize: 10
    reportingTimeIntervalMs: 120000
    description: Participant Policy
    participantId: 101c62b3-8918-41b9-a747-d21eb79c6c03
    kafka:
      bootstrapServers: ${KAFKA_SERVER:kafka:9092}
      authExceptionRetryInterval: 5s
      consumer:
        groupId: policy-clamp-ac-pf-ppnt
      properties:
        security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
        sasl.mechanism: ${KAFKA_SASL_MECHANISM:GSSAPI}
        sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG:}
    participantSupportedElementTypes:
      -
        typeName: org.onap.policy.clamp.acm.PolicyAutomationCompositionElement
        typeVersion: 1.0.0

management:
  tracing:
    export:
      enabled: ${ALLOW_TRACING:false}
    propagation:
      produce: ${TRACING_PROPAGATION_TYPE:W3C}
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${TRACING_EXPORTER_ENDPOINT:}
          transport: ${TRACING_EXPORTER_PROTOCOL:http}
  otlp:
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      access: unrestricted
      show-details: always
      probes:
        enabled: true
      show-components: always

server:
  port: 6969
  ssl:
    enabled: false
  servlet:
    context-path: /onap/policy/clamp/acm/policyparticipant
