spring:
  profiles:
    active: default
  security:
    user:
      name: ${RUNTIME_USER}
      password:  ${RUNTIME_PASSWORD}
  datasource:
    url: jdbc:postgresql://${SQL_HOST:localhost}:${SQL_PORT:5432}/clampacm
    driverClassName: org.postgresql.Driver
    username: ${SQL_USER}
    password: ${SQL_PASSWORD}
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:kafka:9092}
    admin:
      auto-create: ${KAFKA_ALLOW_AUTO_CREATE_TOPICS:true}
      # fail-fast: false # Whether to fail fast if the broker is not available on startup.
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
    properties:
      sasl.mechanism: ${KAFKA_SASL_MECHANISM:GSSAPI}
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG:}
    listener:
      observation-enabled: ${ALLOW_TRACING:false}
    template:
      observation-enabled: ${ALLOW_TRACING:false}
    consumer:
      group-id: ${KAFKA_GROUP_ID:acm-runtime}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.onap.policy.clamp.acm.runtime.supervision.comm.serialization.ParticipantMessageDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.onap.policy.clamp.acm.runtime.supervision.comm.serialization.ParticipantMessageSerializer

server:
  port: 6969
  servlet:
    context-path: /onap/policy/clamp/acm
  error:
    path: /error

runtime:
  topics:
    operationTopic: ${RUNTIME_OPERATION_TOPIC:policy-acruntime-participant}
    syncTopic: ${RUNTIME_SYNC_TOPIC:acm-ppnt-sync}
  participantParameters:
    heartBeatMs: ${HEART_BEAT:120000}
    maxStatusWaitMs: ${MAX_STATUS_WAIT:150000}
    maxOperationWaitMs: ${MAX_OPERATION_WAIT:36000}
  acmParameters:
    toscaElementName: ${TOSCA_ELEMENT_NAME:org.onap.policy.clamp.acm.AutomationCompositionElement}
    toscaCompositionName: ${TOSCA_COMPOSITION_NAME:org.onap.policy.clamp.acm.AutomationComposition}
    enableEncryption: ${MSG_ENABLE_ENCRYPTION:false}

management:
  server:
    port: ${PROMETHEUS_PORT:6970}
    base-path: ${PROMETHEUS_PATH:/onap/policy/clamp/acm}
  tracing:
    propagation:
      produce: ${JAEGER_PRODUCER_TYPE:B3}
    sampling:
      probability: ${JAEGER_SAMPLING_PROBABILITY:1.0}
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      show-components: always
  health:
    db:
      enabled: false

tracing:
  enabled: ${ALLOW_TRACING:false}
  exporter:
    endpoint: ${TRACING_EXPORTER_ENDPOINT:http://jaeger:4318/v1/traces}
    protocol: ${TRACING_EXPORTER_PROTOCOL:http}
  sampler:
    jaeger-remote:
      endpoint: ${TRACING_SAMPLER_ENDPOINT:http://jaeger:14250}

basicAuth: ${BASIC_AUTH:true}
