spring:
  security:
    user:
      name: runtimeUser
      password: zb!XztG34
  http:
    converters:
      preferred-json-mapper: gson
  datasource:
    url: jdbc:mariadb://${mariadb.host:localhost}:${mariadb.port:3306}/controlloop
    driverClassName: org.mariadb.jdbc.Driver
    username: policy
    password: P01icY
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.onap.policy.clamp.controlloop.runtime.config.PhysicalNamingStrategyClImpl
        implicit-strategy: org.onap.policy.clamp.controlloop.runtime.config.CustomImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true

security:
  enable-csrf: false

server:
  port: 6969
  servlet:
    context-path: /onap/controlloop
  error:
    path: /error


runtime:
  participantParameters:
    heartBeatMs: 20000
    maxStatusWaitMs: 100000
    updateParameters:
      maxRetryCount: 4
      maxWaitMs: 20000
  topicParameterGroup:
    topicSources:
      -
        topic: POLICY-CLRUNTIME-PARTICIPANT
        servers:
          - ${topicServer:localhost}
        topicCommInfrastructure: dmaap
        fetchTimeout: 15000
    topicSinks:
      -
        topic: POLICY-CLRUNTIME-PARTICIPANT
        servers:
          - ${topicServer:localhost}
        topicCommInfrastructure: dmaap

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
