spring:
  security:
    user:
      name: healthcheck
      password: zb!XztG34
  http:
    converters:
      preferred-json-mapper: gson

security:
  enable-csrf: false

server:
  port: 6969
  servlet:
    context-path: /onap/controlloop
  error:
    path: /error


runtime:
  supervisionScannerIntervalSec: 1000
  participantClUpdateIntervalSec: 1000
  participantClStateChangeIntervalSec: 1000
  participantParameters:
    heartBeatMs: 120000
    maxMessageAgeMs: 600000
    updateParameters:
      maxRetryCount: 3
      maxWaitMs: 100000
  databaseProviderParameters:
    name: PolicyProviderParameterGroup
    implementation: org.onap.policy.models.provider.impl.DatabasePolicyModelsProviderImpl
    databaseDriver: org.mariadb.jdbc.Driver
    databaseUrl: jdbc:mariadb://${mariadb.host:localhost}:${mariadb.port:3306}/controlloop
    databaseUser: policy
    databasePassword: P01icY
    persistenceUnit: CommissioningMariaDb
  topicParameterGroup:
    topicSources:
      -
        topic: POLICY-CLRUNTIME-PARTICIPANT
        servers:
          - ${topicServer:localhost}
        topicCommInfrastructure: dmaap
        fetchTimeout: 15000
    topicSinks:
      -
        topic: POLICY-CLRUNTIME-PARTICIPANT
        servers:
          - ${topicServer:localhost}
        topicCommInfrastructure: dmaap

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
