server:
  port: 6969
  ssl:
    enabled: false
  servlet:
    context-path: /policy/api/v1

spring:
  security.user:
    name: policyadmin
    password: zb!XztG34
  mvc.converters.preferred-json-mapper: gson
  datasource:
    url: jdbc:postgresql://postgres:5432/policyadmin
    driverClassName: org.postgresql.Driver
    username: policy_user
    password: policy_user
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.onap.policy.common.spring.utils.CustomImplicitNamingStrategy

policy-api:
  name: ApiGroup

database:
  name: PolicyProviderParameterGroup
  implementation: org.onap.policy.models.provider.impl.DatabasePolicyModelsProviderImpl
  driver: org.postgresql.Driver
  url: jdbc:postgresql://postgres:5432/policyadmin
  user: policy_user
  password: policy_user
  persistenceUnit: PolicyDb

policy-preload:
  policyTypes:
  - policytypes/onap.policies.monitoring.tcagen2.yaml
  - policytypes/onap.policies.monitoring.tcagen2.v2.yaml
  - policytypes/onap.policies.monitoring.dcaegen2.collectors.datafile.datafile-app-server.yaml
  - policytypes/onap.policies.monitoring.dcae-restconfcollector.yaml
  - policytypes/onap.policies.monitoring.dcae-pm-subscription-handler.yaml
  - policytypes/onap.policies.monitoring.dcae-pm-mapper.yaml
  - policytypes/onap.policies.Optimization.yaml
  - policytypes/onap.policies.optimization.Resource.yaml
  - policytypes/onap.policies.optimization.Service.yaml
  - policytypes/onap.policies.optimization.resource.AffinityPolicy.yaml
  - policytypes/onap.policies.optimization.resource.DistancePolicy.yaml
  - policytypes/onap.policies.optimization.resource.HpaPolicy.yaml
  - policytypes/onap.policies.optimization.resource.OptimizationPolicy.yaml
  - policytypes/onap.policies.optimization.resource.PciPolicy.yaml
  - policytypes/onap.policies.optimization.service.QueryPolicy.yaml
  - policytypes/onap.policies.optimization.service.SubscriberPolicy.yaml
  - policytypes/onap.policies.optimization.resource.Vim_fit.yaml
  - policytypes/onap.policies.optimization.resource.VnfPolicy.yaml
  - policytypes/onap.policies.controlloop.guard.Common.yaml
  - policytypes/onap.policies.controlloop.guard.common.Blacklist.yaml
  - policytypes/onap.policies.controlloop.guard.common.FrequencyLimiter.yaml
  - policytypes/onap.policies.controlloop.guard.common.MinMax.yaml
  - policytypes/onap.policies.controlloop.guard.common.Filter.yaml
  - policytypes/onap.policies.controlloop.guard.coordination.FirstBlocksSecond.yaml
  - policytypes/onap.policies.Naming.yaml
  - policytypes/onap.policies.Match.yaml
  - policytypes/onap.policies.native.Drools.yaml
  - policytypes/onap.policies.native.Xacml.yaml
  - policytypes/onap.policies.native.Apex.yaml
  - policytypes/onap.policies.controlloop.operational.Common.yaml
  - policytypes/onap.policies.controlloop.operational.common.Apex.yaml
  - policytypes/onap.policies.controlloop.operational.common.Drools.yaml
  - policytypes/onap.policies.native.opa.yaml
  policies:
  - policies/opa.policy.slice.capacity.check.tosca.yaml
  - policies/sdnc.policy.naming.input.tosca.yaml

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,metrics,prometheus
      path-mapping:
        -metrics: plain-metrics
        -prometheus: metrics
