# ============LICENSE_START=======================================================
# Copyright (C) 2021 Nordix Foundation.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# ============LICENSE_END=========================================================
tosca_definitions_version: tosca_simple_yaml_1_3
node_types:
  org.oran.asd.DeploymentItem:
    version: 1.0.1
    derived_from: org.onap.policy.clamp.controlloop.KubernetesControlLoopElement
    properties:
      deployemntItemId:
        type: onap.datatypes.ToscaConceptIdentifier
        required: true
        description: The identifier of this deployment item
      artifactId:
        type: onap.datatypes.ToscaConceptIdentifier
        required: true
        description: Reference to a DeploymentArtifact
      lifecycleParameters:
        type: string
        required: false
        description: List of parameters that can be overridden at deployment time
                     (e.g. values for values.yaml in the chart this item references)
  org.oran.asd.ASD:
    version: 1.0.1
    derived_from: org.onap.policy.clamp.controlloop.ControlLoop
    properties:
      asdId:
        type: onap.datatypes.ToscaConceptIdentifier
        required: true
        description: The identifier of this deployment item
      asdSchemaVersion:
        type: onap.datatypes.ToscaConceptIdentifier
        required: true
        description: Reference to a DeploymentArtifact
      asdApplication:
        type: onap.datatypes.ToscaConceptIdentifier
        required: true
        description: Reference to a DeploymentArtifact
      asdApplicationInfoName:
        type: string
        required: false
        description: Human readable name for the Application service. Can change during the AS lifetime. 
      asdExtCpd:
        type: string
        required: false
        description: Describes external interface(s) exposed by this AS enabling connection with a VL.
                     (Similar to VnfExtCpd on VNF-D, but only describing L3 and above interfaces, since
                     K8S can’t do <L3)
      enhancedClusterCapabilities:
        type: string
        required: false
        description: Describes expected capabilities of the target Kubernetes cluster to aid placement of the
                     application service on a suitable cluster. Examples of capabilities are; required networking
                     characteristics, Kubernetes API extensions or quantifiable node specific resources. This attribute
                     can contain information complementing information provided in the referenced DeploymentArtifacts.
                     Note; Modeling of enhancedClusterCapabilities is subject to standardization but is ffs. Alignment
                     between O2-IMS and O2-DMS of these values is required.



