spring:
  security:
    user:
      name: ${REST_USER}
      password: ${REST_PASSWORD}

server:
  port: ${PORT}
  ssl:
    enabled: false
  error:
    path: /error

element:
  elementId:
    name: ${ELEMENT_ID}
    version: ${ELEMENT_VERSION}
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics, prometheus
